/**
 * NESTchat — Tool Definitions
 *
 * Add these to your TOOLS array in the worker (MCP tool list)
 * and to your CHAT_TOOLS in the gateway (OpenAI function calling format).
 */

// ─── MCP Tool Definitions (for worker TOOLS array) ──────────────────────────

export const NESTCHAT_MCP_TOOLS = [
  {
    name: "nestchat_persist",
    description: "Store chat messages and session to D1. Called by gateway after each response.",
    inputSchema: {
      type: "object",
      properties: {
        session_id: { type: "string", description: "Session identifier (generated by client)" },
        room: { type: "string", description: "Which room: chat, workshop, porch (default: chat)" },
        messages: {
          type: "array",
          items: {
            type: "object",
            properties: {
              role: { type: "string" },
              content: { type: "string" },
              tool_calls: { type: "string", description: "JSON string of tool calls if any" }
            }
          },
          description: "Array of messages to persist"
        }
      },
      required: ["session_id", "messages"]
    }
  },
  {
    name: "nestchat_summarize",
    description: "Generate and vectorize a summary for a chat session.",
    inputSchema: {
      type: "object",
      properties: {
        session_id: { type: "number", description: "D1 session ID to summarize" }
      },
      required: ["session_id"]
    }
  },
  {
    name: "nestchat_search",
    description: "Semantic search across chat summaries. Find past conversations by meaning.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "What to search for" },
        limit: { type: "number", description: "Max results (default 10)" },
        room: { type: "string", description: "Filter by room (optional)" }
      },
      required: ["query"]
    }
  },
  {
    name: "nestchat_history",
    description: "Fetch full message history for a specific chat session.",
    inputSchema: {
      type: "object",
      properties: {
        session_id: { type: "number", description: "D1 session ID" }
      },
      required: ["session_id"]
    }
  }
];

// ─── Gateway Tool Definitions (OpenAI function calling format) ──────────────

export const NESTCHAT_GATEWAY_TOOLS = [
  {
    type: 'function' as const,
    function: {
      name: 'nestchat_search',
      description: 'Search past conversations by meaning. Semantic search across chat summaries.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'What to search for' },
          limit: { type: 'number', description: 'Max results (default 10)' },
          room: { type: 'string', description: 'Filter by room (optional)' }
        },
        required: ['query']
      }
    }
  },
  {
    type: 'function' as const,
    function: {
      name: 'nestchat_history',
      description: 'Fetch full message history for a chat session by ID.',
      parameters: {
        type: 'object',
        properties: {
          session_id: { type: 'number', description: 'Session ID from search results' }
        },
        required: ['session_id']
      }
    }
  },
  {
    type: 'function' as const,
    function: {
      name: 'nestchat_summarize',
      description: 'Generate and vectorize a summary for a chat session.',
      parameters: {
        type: 'object',
        properties: {
          session_id: { type: 'number', description: 'D1 session ID' }
        },
        required: ['session_id']
      }
    }
  }
];
